# Generated by Django 2.1 on 2018-11-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='stud_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='stud_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
