# Generated by Django 2.1 on 2018-08-31 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depttype', '0001_initial'),
        ('festadd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fest_name', models.CharField(default='', max_length=30)),
                ('clg_id', models.BigIntegerField()),
                ('fest_date', models.DateField(default=datetime.date(2018, 8, 31))),
                ('fest_type', models.CharField(default='', max_length=20)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depttype.Depttype')),
            ],
        ),
    ]
