# Generated by Django 2.1 on 2018-09-22 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festadd', '0002_festadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festadd',
            name='fest_date',
            field=models.DateField(default=datetime.date(2018, 9, 22)),
        ),
    ]
