# Generated by Django 2.1 on 2018-09-27 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festadd', '0003_auto_20180922_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festadd',
            name='fest_date',
            field=models.DateField(default=datetime.date(2018, 9, 28)),
        ),
    ]
