# Generated by Django 2.1 on 2018-10-06 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festadd', '0005_auto_20181006_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festadd',
            name='fest_date',
            field=models.DateField(default=datetime.date(2018, 10, 7)),
        ),
    ]
