# Generated by Django 2.1 on 2018-10-20 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festadd', '0007_auto_20181019_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festadd',
            name='fest_date',
            field=models.DateField(default=datetime.date(2018, 10, 20)),
        ),
    ]
