# Generated by Django 2.1 on 2018-10-21 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festadd', '0008_auto_20181020_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='festadd',
            name='fest_theme',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='festadd',
            name='fest_date',
            field=models.DateField(default=datetime.date(2018, 10, 21)),
        ),
    ]
