# Generated by Django 2.1 on 2018-11-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaintreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.BigIntegerField()),
                ('comp_desc', models.CharField(default='', max_length=30)),
                ('comp_date', models.CharField(default='', max_length=30)),
                ('comp_status', models.CharField(default='', max_length=30)),
                ('comp_reply', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
