# Generated by Django 2.1 on 2018-11-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaintreg', '0002_auto_20181120_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintreg',
            name='stud_id',
        ),
    ]
