# Generated by Django 2.1 on 2018-10-20 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collegecoordreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_name', models.CharField(default='', max_length=30)),
                ('coord_contactno', models.CharField(default='', max_length=15)),
                ('coord_email', models.CharField(default='', max_length=30)),
                ('clg_name', models.CharField(default='', max_length=30)),
                ('clg_website', models.CharField(default='', max_length=30)),
                ('clg_contactno', models.CharField(default='', max_length=30)),
                ('clg_place', models.CharField(default='', max_length=30)),
                ('clg_pincode', models.CharField(default='', max_length=30)),
                ('clg_dist', models.CharField(default='', max_length=30)),
                ('clg_startdate', models.DateField(default=datetime.date.today)),
                ('clg_licenceno', models.CharField(default='', max_length=30)),
                ('clg_type', models.CharField(default='', max_length=30)),
                ('clg_username', models.CharField(default='', max_length=30)),
                ('clg_password', models.CharField(default='', max_length=30)),
                ('clg_status', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
