# Generated by Django 2.1 on 2018-10-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegecoordreg', '0001_initial'),
        ('depttype', '0001_initial'),
        ('studreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(default='', max_length=30)),
                ('stud_place', models.CharField(default='', max_length=30)),
                ('stud_email', models.CharField(default='', max_length=30)),
                ('stud_contactno', models.CharField(default='', max_length=30)),
                ('stud_age', models.CharField(default='', max_length=30)),
                ('stud_admno', models.CharField(default='', max_length=30)),
                ('stud_course', models.CharField(default='', max_length=30)),
                ('stud_batch', models.CharField(default='', max_length=30)),
                ('stud_username', models.CharField(default='', max_length=30)),
                ('stud_password', models.CharField(default='', max_length=30)),
                ('stud_status', models.CharField(default='', max_length=30)),
                ('clg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegecoordreg.Collegecoordreg')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depttype.Depttype')),
            ],
        ),
    ]
