# Generated by Django 2.1 on 2018-10-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festadd', '0007_auto_20181019_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=30)),
                ('event_desc', models.CharField(default='', max_length=50)),
                ('event_fees', models.IntegerField(max_length=3)),
                ('part_type', models.CharField(default='', max_length=10)),
                ('max_part', models.IntegerField(default='0', max_length=3)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('fest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festadd.Festadd')),
            ],
        ),
    ]
