# Generated by Django 2.1 on 2018-10-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventadd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadd',
            name='venue',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='fest_id',
            field=models.BigIntegerField(),
        ),
    ]
