# Generated by Django 2.1 on 2018-10-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventadd', '0002_auto_20181021_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='fest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festadd.Festadd'),
        ),
    ]
