# Generated by Django 2.1 on 2018-10-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventadd', '0003_auto_20181021_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventadd',
            name='clg_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
