# Generated by Django 2.1 on 2018-10-21 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventadd', '0004_eventadd_clg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='time_from',
            field=models.TimeField(verbose_name=datetime.time),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='time_to',
            field=models.TimeField(verbose_name=datetime.time),
        ),
    ]
