# Generated by Django 2.1 on 2018-10-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventadd', '0006_auto_20181021_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='event_fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='max_part',
            field=models.IntegerField(),
        ),
    ]
