# Generated by Django 2.1 on 2018-10-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventadd', '0007_auto_20181021_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadd',
            name='event_fees',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='max_part',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='time_from',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='eventadd',
            name='time_to',
            field=models.CharField(default='', max_length=6),
        ),
    ]
