# Generated by Django 2.1 on 2018-11-11 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventadd', '0008_auto_20181021_1352'),
        ('studreg', '0002_studreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_reg_no', models.IntegerField()),
                ('payment_status', models.CharField(default='', max_length=5)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventadd.Eventadd')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studreg.Studreg')),
            ],
        ),
    ]
